### ISSUE TITLE
Sparrow.js and newer Node versions

### ISSUE THREAD

**Issue by knellr** [r8k/sparrow.js#7]
I tried to install sparrow.js today (on a Mac with Yosemite) and noticed that I couldn't get it working with Node 0.12.0 - httprequest seems to have broken, and is deprecated:

```
npm WARN deprecated httpsync@0.0.8: This module no longer work, please use urllib-sync instead.
```

I later get the following error, among others, when running npm install sparrow.js:

```
In file included from ../src/main.cc:1:
../src/./curl.h:11:31: error: expected class name
class NodeCurl : public node::ObjectWrap {
                              ^
../src/./curl.h:16:45: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        static Handle<Value> request (const Arguments&);
                                            ^~~~~~~~~
                                            v8::internal::Arguments
```

The install worked fine when I reverted to Node 0.10.38. Are there plans to support later versions of Node?

**Comment by r8k** [comment]
@knellr - I'm looking into this, and will let you know as soon as possible. Thanks for using sparrow.

**Comment by luckykurhe** [comment]
was there any solution on this ticket ? 
I am also getting same error - but not at all related to sparrowJS (am not installing sparrowJS) (posting here as error is same)
problem seems specific to some other issue.. 

Making all in include
Making all in curl
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[3]: Nothing to be done for `all-am'.
make[2]: Nothing to be done for`all-am'.
make[1]: Nothing to be done for `all-am'.
  CXX(target) Release/obj.target/node_curl/src/main.o
In file included from ../src/main.cc:1:
../src/./curl.h:11:31: error: expected class name
class NodeCurl : public node::ObjectWrap {
                              ^
../src/./curl.h:16:45: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        static Handle<Value> request (const Arguments&);
                                            ^~~~~~~~~
                                            v8::internal::Arguments
/Users/myUserID/.node-gyp/4.0.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/main.cc:1:
../src/./curl.h:17:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        static Handle<Value> get (const Arguments&);
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/myUserID/.node-gyp/4.0.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/main.cc:1:
../src/./curl.h:18:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        static Handle<Value> post (const Arguments&);
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/myUserID/.node-gyp/4.0.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/main.cc:1:
../src/./curl.h:31:43: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        static Handle<Value> write (const Arguments&);
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/myUserID/.node-gyp/4.0.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/main.cc:1:
../src/./curl.h:33:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        static Handle<Value> end (const Arguments&);
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/myUserID/.node-gyp/4.0.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/main.cc:1:
../src/./curl.h:35:45: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        static Handle<Value> endFile (const Arguments&);
                                            ^~~~~~~~~
                                            v8::internal::Arguments
/Users/myUserID/.node-gyp/4.0.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
7 errors generated.
make: *** [Release/obj.target/node_curl/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/myUserID/pathToMyProject/test/node_modules/httpsync
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
building for mac
clang: error: no such file or directory: 'build/Release/obj.target/node_curl/src/curl.o'
clang: error: no such file or directory: 'build/Release/obj.target/node_curl/src/main.o'
clang: error: no such file or directory: 'build/Release/obj.target/node_curl/src/request.o'
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! httpsync@0.0.8 install: `sh build.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the httpsync@0.0.8 install script 'sh build.sh'.
npm ERR! This is most likely a problem with the httpsync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh build.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls httpsync
npm ERR! There is likely additional logging output above.

note:
myUserID - is my userid
pathToMyProject - is path to my project

**Comment by luckykurhe** [comment]
Found solution to this error : its in first line itself
"npm WARN deprecated httpsync@0.0.8: This module no longer work, please use urllib-sync instead."
Tried it and everything works good.
Mac OS version was: 10.10.5
